defaults: &defaults
  enju:
    erms_url: 
    skip_mobile_agents:
      - ipad

  family_name_first: true
  max_number_of_results: 500
  write_search_log_to_file: true
  csv_charset_conversion: true

# Choose a locale from 'ca', 'de', 'fr', 'jp', 'uk', 'us'
#AMAZON_AWS_HOSTNAME = 'ecs.amazonaws.com'
  amazon:
    aws_hostname: ecs.amazonaws.jp
    hostname: www.amazon.co.jp
    access_key_id: REPLACE_WITH_YOUR_AMAZON_ACCESS_KEY
    secret_access_key: REPLACE_WITH_YOUR_AMAZON_SECRET_ACCESS_KEY
    bucket: enju_leaf

# :google, :amazon
  book_jacket:
    source: :google
    unknown_resource: 

# :mozshot, :simpleapi, :heartrails, :thumbalizr
  screenshot:
    generator: :mozshot

  uploaded_file:
    storage: :local

  manifestation:
    facet:
      pub_year_range_interval: 10

  news_post:
    number:
      top_page: 3

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
